config/routes.rb
Nocios::Application.routes.draw do
  devise_for :users

  
  root :to => "statistics#index"
  
  match '/search' => "statistics#search", :as => :search
  
  resources :hosts do 
    resources :checks do
      get :graph, :on => :member
    end
  end
  
  resources :users
  
  resource :api, :only => [:create_host, :get_data] do 
    collection do 
      post 'create_host'
      get 'get_data'
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
    if user.id == 1
      can :manage, :all
    end
  end
end

app/models/check.rb
class Check < ActiveRecord::Base
  belongs_to :host
  has_many :results
  
  serialize :params
  
  def run
    if self.active?
      self.delay(:run_at => self.frequency.minutes.from_now).run
    end
    r = self.results.build
    begin
      p = nil
      unless self.params.empty?
	p = JSON.parse(self.params)
      end
      r.output = command.constantize.perform(self.host, p)
      r.successful = true
    rescue => e
      r.output = e
      r.successful = false
    ensure 
      r.save
    end
  end
  
  def graph?
    command.constantize.respond_to?('graph')
  end
  
  def graph
    command.constantize.graph(results)
  end
  
  def series
    s = []
    results.each do |r|
      s << [r.created_at, r.output]
    end
    {:name => '', :data => s}
  end
  
  def active?
    host.active? || self.active
  end
  
  def monitored?
    !Delayed::Job.where("handler like '%ActiveRecord:Check%' and handler like '%id: #{self.id}%'").empty?
  end
  
  def as_json(options={})
    super(:include => :results)
  end
end

app/models/host.rb
class Host < ActiveRecord::Base
  has_many :checks, :dependent => :destroy
  
  accepts_nested_attributes_for :checks
  
  acts_as_taggable
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :check
  
  serialize :output
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :token_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :login, :password, :password_confirmation, :remember_me
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  before_filter :authenticate_user!
  
  respond_to :json
  
  def create_host
    
    # host.checks.run
  end
  
  def get_data
    check = Check.find(params[:id])
    #delete results marked
    #mark results sent for deletion if not to store localy
    respond_with(check.to_json(:include => :results))
  end
  
  def skip_auth?
    true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  check_authorization :unless => :skip_auth?
  
  def skip_auth?
    if devise_controller?
      true
    else
      false
    end
  end
end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  
  def index
    @host = Host.find(params[:host_id])
    @checks = @host.checks.paginate(:page => params[:page])
  end
  
  def show
    @host = Host.find(params[:host_id])
    @check = Check.find(params[:id])
    @disabled = true
    respond_to do |format|
      format.html
      format.json { render :json => @check}
    end
  end
  
  def edit
    @host = Host.find(params[:host_id])
    @check = Check.find(params[:id])
    @disabled = false
  end
  
  def new
    @host = Host.find(params[:host_id])
    @check = @host.checks.build
    @disabled = false
  end
  
  def update
    @check = Check.find(params[:id])
    @check.update_attributes(params[:check])
    if @check.save
      flash[:success] = "Check Successfuly Updated"
    else
      flash[:error] = "Check not Updated"
    end
    redirect_to host_checks_path(@host)
  end
  
  def create
    @check = Check.new(params[:check])
    if @check.save
      flash[:success] = "Check Successfuly Created"
    else
      flash[:error] = "Check not Created"
    end
    redirect_to host_checks_path(@host)
  end
  
  def destroy
    @check = Check.find(params[:id])
    if @check.destroy
      flash[:success] = "Check Successfuly Destroyed"
    else
      flash[:error] = "Check Not Destroyed"
    end
    redirect_to host_checks_path(@host)
  end
  
  def graph
    @check = Check.find(params[:id])
    name = @check.command
    respond_to do |format|
      format.json {
	if @check.graph?
	  render :json => {:title => "#{@check.host.name} - #{@check.name}", :series => @check.graph, :interval => @check.frequency*1000*60}
	else
	  render :json => {:title => "#{@check.host.name} - #{@check.name}", :series => @check.series, :interval => @check.frequency*1000*60}
        end
      }
    end
  end
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  
  def index
    @hosts = Host.order('name asc').paginate(:page => params[:page])
  end
  
  def show
    @host = Host.find(params[:id])
    @disabled = true
  end
  
  def edit
    @host = Host.find(params[:id])
    @disabeld = false
  end
  
  def new
    @host = Host.new
    @disabled = false
  end
  
  def update
    @host = Host.find(params[:id])
    if @host.update_attributes(params[:host])
      flash[:success] = "Host Successfullty Updated"
    else
      flash[:error] = "Host Not Updated"
    end
    redirect_to hosts_path
  end
  
  def create
    @host = Host.new(params[:host])
    if @host.save
      flash[:success] = "Host Successfully Created"
    else
      flash[:error] = "Host Not Created"
    end
    redirect_to hosts_path
  end
  
  def destroy
    @host = Host.find(params[:id])
    if @host.destroy
      flash[:success] = "Host Successfully Destroyed"
    else
      flash[:error] = "Host Not Destroyed"
    end
    redirect_to hosts_path
  end
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  
  def index
    @hosts_count = Host.where(:active => true).all.count
    @checks_count = Check.where(:active => true).all.count
  end
  
  def skip_auth?
    true
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_filter :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bootstrap_helper.rb
module BootstrapHelper
  def horizontal_form_field(item, lbl)
    content_tag :div, :class => 'control-group' do 
      content_tag(:label, lbl, :class => 'control-label')+
      content_tag(:div, :class => 'controls') do 
        item
      end
    end
  end
end

app/helpers/host_helper.rb
module HostHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/checks/_form.html.haml
=form_for [@host,@check], :html => {:class => 'form-horizontal'} do |f|
  %fieldset
    %legend Check
    =f.hidden_field(:host_id, :value => @host.id)
    =horizontal_form_field f.hidden_field(:id, :value => @check.id), ""
    =horizontal_form_field f.text_field(:name, :disabled => @disabled), "Name"
    =horizontal_form_field f.text_field(:command, :disabled => @disabled), "Command"
    =horizontal_form_field f.text_area(:params, :disabled => @disabled, :value => @check.params, :rows => 4), "Parameters"
    =horizontal_form_field f.text_field(:frequency, :disabled => @disabled), "Frequency (min)"
    =horizontal_form_field f.text_field(:keep_for, :disabled => @disabled), "Keep For (min)"
    =horizontal_form_field f.check_box(:active, :disabled => @disabled), "Active"

    .form-actions
      -unless @disabled
        =f.submit "Save", :class => 'btn btn-primary'
      -else
        -if can? :manage, @host
          =link_to "Edit", edit_host_check_path(@host, @check), :class => 'btn btn-warning'
      =link_to "Back", :back, :class => 'btn btn-inverse'

app/views/checks/edit.html.haml
=render :partial => "form"

app/views/checks/index.html.haml
%table.table.table-striped{:width => '100%'}
  %thead
    %tr
      %th ID
      %th Name
      %th Command
      %th Params
      %th Active
      %th Actions
  %tbody
    -@checks.each do |c|
      %tr
        %td=c.id
        %td=c.name
        %td=c.command
        %td=c.params
        %td=c.active
        %td
          =link_to "Show", host_check_path(@host, c), :class => "btn btn-primary"
          -if can? :manage, c
            =link_to "Edit", edit_host_check_path(@host, c), :class => "btn btn-warning"
            =link_to "Destroy", host_check_path(@host, c), :method => :destroy, :confirm => "Are you sure?", :class => "btn btn-danger"
.row
  =link_to "New Check", new_host_check_path(@host), :class => "btn btn-success", :style => "float:right"
  =will_paginate @checks

app/views/checks/new.html.haml
=render :partial => "form"

app/views/checks/show.html.haml
.row
  .span6
    =render :partial => "form"
  .span6
    #check_graph{:data => {:check_id => @check.id, :host_id => @check.host_id}}

app/views/hosts/_form.html.haml
=form_for @host, :html => {:class => 'form-horizontal'} do |f|
  %fieldset
    %legend Host
    =horizontal_form_field f.hidden_field(:id, :value => @host.id), ""
    =horizontal_form_field f.text_field(:name, :disabled => @disabled), "Name"
    =horizontal_form_field f.text_field(:address, :disabled => @disabled), "Address"
    =horizontal_form_field f.text_field(:ssh_user, :disabled => @disabled), "SSH User"
    =horizontal_form_field f.password_field(:ssh_password, :disabled => @disabled), "SSH Password"
    =horizontal_form_field f.text_field(:telnet_user, :disabled => @disabled), "Telnet User"
    =horizontal_form_field f.password_field(:telnet_password, :disabled => @disabled), "Telnet Password"
    =horizontal_form_field f.text_field(:snmp_community, :disabled => @disabled), "Snmp Community"
    =horizontal_form_field f.check_box(:active, :disabled => @disabled), "Active"

    .form-actions
      -unless @host.id.nil?
        =link_to "Checks", host_checks_path(@host), :class => "btn btn-info"
      -unless @disabled
        =f.submit "Save", :class => 'btn btn-primary'
      -else
        -if can? :manage, @host
          =link_to "Edit", edit_host_path(@host), :class => 'btn btn-warning'
      =link_to "Back", :back, :class => 'btn btn-inverse'

app/views/hosts/edit.html.haml
=render :partial => "form"

app/views/hosts/index.html.haml
%table.table.table-striped{:width => '100%'}
  %thead
    %tr
      %th ID
      %th Name
      %th Address
      %th Actions
  %tbody
    -@hosts.each do |h|
      %tr
        %td=h.id
        %td=h.name
        %td=h.address
        %td
          =link_to "Show", host_path(h), :class => "btn btn-primary"
          =link_to "Checks", host_checks_path(h), :class => "btn btn-info"
          -if can? :manage, h
            =link_to "Edit", edit_host_path(h), :class => "btn btn-warning"
            =link_to "Destroy", host_path(h), :method => :destroy, :confirm => "Are you sure?", :class => "btn btn-danger"
.row
  =link_to "New Host", new_host_path, :class => "btn btn-success", :style => "float:right"
  =will_paginate @hosts

app/views/hosts/new.html.haml
=render :partial => "form"

app/views/hosts/show.html.haml
.row
  .span6  
    =render :partial => "form"
  .span6
    #graphs

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title Nocios
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a{:class => "btn btn-navbar", :data => {:toggle => "collapse", :target => ".nav-collapse"}}
            %span.icon-bar
            %span.icon-bar
          =link_to "Nocios", root_path, :class => 'brand'
          -if current_user
            .nav-collapse
              %ul.nav
                %li= link_to "Hosts", hosts_path
              %ul.nav.pull-right
                %li=link_to current_user.login, user_path(current_user), :class => 'pull-right'
              =form_tag search_path, :class => "navbar-search pull-right" do
                %input.search-query{:type => 'text', :placeholder => "Search"}

          -else
            .nav-collapse
              =form_for "user", :url => user_session_path, :class => "form-inline navbar-search pull-right" do |f|
                =f.text_field :login, :class => "search-query input-medium", :placeholder => "Login"
                =f.password_field :password, :class => "search-query input-medium", :placeholder => "Password"
                =f.submit "Sign in", :class => "btn"


    .container
      -flash.each do |type, msg|
        .alert{:class => "alert-#{type}"}
          %a.close{:data => {:dismiss => "alert"}} x
          =msg
      = yield

app/views/statistics/index.html.haml
%form.form-horizontal
  %fieldset
    %legend Statistics
    =horizontal_form_field(text_field_tag(:host_number, @hosts_count, :class => 'input-small', :disabled => true), "Monitored Host Count")
    =horizontal_form_field(text_field_tag(:check_count, @checks_count, :class => 'input-small', :disabled => true), "Monitored Check Count")